### ISSUE TITLE
Default masthead feature

### ISSUE THREAD

**Issue by dpardons** [TLWebdesign/Pretty-Masthead#2]
Hi

Default masthead seems not to work as described and my understanding.
Module assigned to a page but not defined with a specific masthead associated to the page menu item.
Result: the default masthead is not displayed. Must be displayed in my understanding.
(tested on localhost with cassiopeia template)
Regards

Daniel

**Comment by TLWebdesign** [comment]
Hi Daniel, can you show me a screen of your default masthead settings? Then i can try to replicate it. below is a screenshot of my default setting and it's working fine.
<img width="1589" alt="Schermafbeelding 2022-08-05 om 17 01 31" src="https://user-images.githubusercontent.com/4402824/183104976-bbedb6cb-58fb-4e4f-a60e-eb20b8acd28e.png">

**Comment by dpardons** [comment]
Hi
Copy of the default masthead settings
[Regards])
Daniel
![Screenshot_2](https://user-images.githubusercontent.com/2719490/183114453-e0cb97a0-4c7d-4a46-8876-28d984302ba1.jpg)

**Comment by TLWebdesign** [comment]
Hmm everything filled out so thats not the issue. Have you checked your console to see if the html is there or not? Wondering if it's a template issue or that there is no data available. What template are you using? if you know how to var_dump you could do a var_dump($masthead) in mod_prettymasthead/tmpl/default.php on line 16 after the php opening tag. Like to know if that displays empty vars or not.

**Comment by dpardons** [comment]
Hi
The generated html is the following:
			<div class="pretty-masthead">
		</div>

Using joomla basic template Cassiopeia with j4 last version. 

Dump is the following:
array(1) { [1]=> array(7) { ["image"]=> string(30) "images/headers/walden-pond.jpg" ["title"]=> string(22) "Title masthead default" ["description"]=> string(28) "Description masthead default" ["position"]=> string(6) "center" ["titletag"]=> string(2) "h1" ["titleclass"]=> string(26) " py-1 py-sm-2 px-3 px-sm-5" ["descriptionclass"]=> string(31) "bg-secondary p-1 py-sm-2 p-sm-3" } }

**Comment by TLWebdesign** [comment]
Hi, hmm so the data is there. That would mean there should be html code there too. Were you able to verify that? 
What browser and browser version are you using?

**Comment by TLWebdesign** [comment]
What module position are you using?

**Comment by TLWebdesign** [comment]
If you could please do a var_dump($imageObj) on line 19. See if that is populated with the height and width.

**Comment by dpardons** [comment]
Hi
Sorry, was away.
1) html generated:
				<div class="container-banner full-width">
				<div class="pretty-masthead">
        </div>
			</div>

2) template Cassiopeia, "banner" position
3) var_dump($imageObj):
object(stdClass)#1753 (2) { ["attributes"]=> array(2) { ["width"]=> int(0) ["height"]=> int(0) } ["url"]=> string(30) "images/headers/walden-pond.jpg" }

**Comment by dpardons** [comment]
<div class="pretty-masthead">
        </div>

**Comment by dpardons** [comment]
Firefox 103.0.1 (64 bits)
Chrome Version 104.0.5112.81 (Build officiel) (64 bits)

**Comment by TLWebdesign** [comment]
I see the issue. Your var dump of imageobj showed 0 for height and width. I use it to calculate the ratio of the div. Need to come up with a fallback solution here. Wasn't expecting joomla to not get that info when there was a valid image. I'll get to it this weekend and come up with a fix. Thanks for all your work in helping me figure out the issue. Weird thing is on my side it does show width and height of that image so i figure it's something to do with php environment.

**Comment by dpardons** [comment]
PHP 7.4.29 on localhost (Laragon)
Joomla configuration:
- Search Engine Friendly URLs: Yes
- Use URL Rewriting: No
- Add Suffix to URL: No
- Unicode Aliases: No
- System Cache: OFF
- Gzip Page Compression: No
- Force HTTPS: No
This seems totally dependant of the picture in use. I tried lot of jpg, png pictures for specific menu masthead and only (the first I choosed was working)
Have a good WE
Daniel

**Comment by TLWebdesign** [comment]
Hi, ok so your var_dump of the image doesn't contain the joomla4 image url like this:

images/headers/blue-flower.jpg#joomlaImage://local-images/headers/blue-flower.jpg?width=700&height=180

But instead looks like this: 

images/headers/walden-pond.jpg

That is why the module was not working correctly. Because it was expecting an URL like in the first example. 
To mitigate this issue i've added an extra check in the helper to see if these values are present and if they are not, to parse the image to make sure they are present. 

I'll put out another release shortly.

**Comment by dpardons** [comment]
HI
New version 0.2.3 works perfectly.
May be one extra remark. If you are "very lazy" and you define the module on "all pages" with a default masthead and a masthead for a specific page, the result on the specific page is that the specific masthead is displayed and followed also by the default one.
My initial understanding of the module was to provide one masthead per page and only one. If there is a specific page masthead, do not take into account if the same page is also defined as default masthead page.

Fine works

Regards
Daniel

**Comment by TLWebdesign** [comment]
> HI New version 0.2.3 works perfectly. May be one extra remark. If you are "very lazy" and you define the module on "all pages" with a default masthead and a masthead for a specific page, the result on the specific page is that the specific masthead is displayed and followed also by the default one. My initial understanding of the module was to provide one masthead per page and only one. If there is a specific page masthead, do not take into account if the same page is also defined as default masthead page.
> 
> Fine works
> 
> Regards Daniel

Hi this it shouldn't do. But i can't seem to replicate the issue. I set a masthead module to display on all pages. filled in default masthead and then added a menu item for a masthead. When visiting the menu item i only see the specific masthead. NO default masthead shown. 

Can you share more info on tour settings?

**Comment by TLWebdesign** [comment]
ok i changed some code to fix this possible issue. now the module only ever returns one masthead. it sets default first and default gets overridden when menu item specific is present.

**Comment by dpardons** [comment]
Totally perfect.
No more remark
Thanks for quick resolution.
Regards
Daniel
